# Generated by Django 5.2.7 on 2025-10-16 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
